// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3AKWIl7MltPb2pweAM8tj-QjgmGkiDwM',
    appId: '1:219116189435:web:a27a96ec08ef661575625e',
    messagingSenderId: '219116189435',
    projectId: 'heallife-63938',
    authDomain: 'heallife-63938.firebaseapp.com',
    databaseURL: 'https://heallife-63938-default-rtdb.firebaseio.com',
    storageBucket: 'heallife-63938.appspot.com',
    measurementId: 'G-MTDKSHD65G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnaPoPxlsx9_8XKYupy81r1MDTduzyjhk',
    appId: '1:219116189435:android:0047faca38a9c09475625e',
    messagingSenderId: '219116189435',
    projectId: 'heallife-63938',
    databaseURL: 'https://heallife-63938-default-rtdb.firebaseio.com',
    storageBucket: 'heallife-63938.appspot.com',
  );
}
